"""empty message

Revision ID: a4f146bbeb5a
Revises: a6e0fef7b018
Create Date: 2022-03-25 13:01:09.688406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f146bbeb5a'
down_revision = 'a6e0fef7b018'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'processed')
    # ### end Alembic commands ###
