"""empty message

Revision ID: a6e0fef7b018
Revises: 
Create Date: 2022-03-25 11:54:26.889892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e0fef7b018'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('tax_code', sa.String(), nullable=True),
    sa.Column('kpp', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_tokens',
    sa.Column('crm_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('validate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['crm_id'], ['crm.id'], ondelete='CASCADE')
    )
    op.create_table('hybrid_tokens',
    sa.Column('crm_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crm_id'], ['crm.id'], ondelete='CASCADE')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('crm_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['crm_id'], ['crm.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('hybrid_tokens')
    op.drop_table('access_tokens')
    op.drop_table('partners')
    op.drop_table('crm')
    # ### end Alembic commands ###
