"""empty message

Revision ID: ab276b39567c
Revises: 
Create Date: 2022-03-25 07:42:24.638645

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ab276b39567c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('access_tokens',
                    sa.Column('crm_id', sa.String(), nullable=False),
                    sa.Column('access_token', sa.String(), nullable=True),
                    sa.Column('validate', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['crm_id'], ['crm.id'], ondelete='CASCADE')
                    )
    op.create_table('hybrid_tokens',
                    sa.Column('crm_id', sa.String(), nullable=False),
                    sa.Column('access_token', sa.String(), nullable=True),
                    sa.Column('refresh_token', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['crm_id'], ['crm.id'], ondelete='CASCADE')
                    )
    op.create_table('payments',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('crm_id', sa.String(), nullable=False),
                    sa.Column('title', sa.String(length=256), nullable=False),
                    sa.Column('description', sa.String(length=2048), nullable=True),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('receiver', sa.String(length=256), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['crm_id'], ['crm.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('hybrid_tokens')
    op.drop_table('access_tokens')
    op.drop_table('crm')
    # ### end Alembic commands ###
